export const workoutSession = {
    session: [
        {
            id: 12394,
            reps: 2,
            weight: 0,
            time: 60,
            rest: 1,
            exerciseToWork: {
                id: 101,
                name: "Trote ligero en el lugar",
                muscles: ["Cuádricep"],
                difficulty: "Baja",
                indications: "Realiza un trote suave en el lugar para aumentar la circulación y preparar los músculos para el ejercicio.",
                preparation: "Mantén los pies ligeros y asegúrate de tener espacio suficiente para moverte sin obstáculos.",
                modalidad: "Cardiovascular",
                material: [],
                type: "Calentamiento",
                injury: "",
            },
        },
        {
            id: 23004,
            reps: 10,
            weight: 0,
            time: 0,
            rest: 30,
            exerciseToWork: {
                id: 102,
                name: "Estiramiento de piernas",
                muscles: ["Femoral"],
                difficulty: "Baja",
                indications: "Realiza movimientos controlados para aumentar la flexibilidad y rango de movimiento.",
                preparation: "Sujétate a una pared o a un objeto estable para mantener el equilibrio si es necesario.",
                material: [],
                type: "Calentamiento",
                injury: "",
            },
        },
        {
            id: 20001,
            reps: 15,
            weight: 0,
            time: 0,
            rest: 30,
            exerciseToWork: {
                id: 103,
                name: "Elevaciones de talón",
                muscles: ["Pantorilla"],
                difficulty: "Baja",
                indications: "Eleva los talones para activar las pantorrillas, mejorando la estabilidad y la propulsión.",
                preparation: "Mantén una postura erguida y si necesitas, usa un soporte para equilibrarte.",
                material: [],
                type: "Calentamiento",
                injury: "",
            },
        },
        {
            id: 20000,
            reps: 10,
            weight: 0,
            time: 0,
            rest: 30,
            exerciseToWork: {
                id: 104,
                name: "Sentadillas suaves",
                muscles: ["Glúteo"],
                difficulty: "Baja",
                indications: "Fortalece y calienta los músculos glúteos y de las piernas con sentadillas suaves.",
                preparation: "Asegúrate de mantener la espalda recta y no dejar que las rodillas sobrepasen los dedos de los pies.",
                material: [],
                type: "Calentamiento",
                injury: "",
            },
        }
    ]
}