export const BodyMeasures = [
    {
        id: 123,
        usuario: 1,
        fecha: "2021-01-20",
        cuello: 10,
        pecho: 11,
        hombros: 12,
        biceps: 13,
        antebrazo: 14,
        cintura: 15,
        cadera: 16,
        pantorrillas: 17,
        muslos: 18,
        peso: 70,
        porcentajeDeGrasa: 20,
        IMC: 21,
        masaMuscularNeta: 22,
        ritmoCardiacoEnReposo: 23,
        presionArterial: 24,
    },
    {
        id: 124,
        usuario: 1,
        fecha: "2021-01-21",
        cuello: 11,
        pecho: 12,
        hombros: 13,
        biceps: 14,
        antebrazo: 15,
        cintura: 16,
        cadera: 17,
        pantorrillas: 18,
        muslos: 19,
        peso: 71,
        porcentajeDeGrasa: 21,
        IMC: 22,
        masaMuscularNeta: 23,
        ritmoCardiacoEnReposo: 24,
        presionArterial: 25,
    }
]